version: '3'

services: 
    declutter-reddit:
        build: . 
        command: ./node_modules/.bin/nodemon server.js
        volumes: 
            - .:/usr/src/app
        ports: 
            - "3000:3000"