version: '3'

services: 
    declutter-reddit:
        build: . 
        command: ./node_modules/.bin/nodemon --exec "node --inspect=0.0.0.0:9229 --require ts-node/register -r dotenv/config declutter-reddit.ts"
        volumes: 
            - .:/usr/src/app
        ports: 
            - "3000:3000"
            - "9229:9229"
        depends_on: 
            - db-reddit
        environment: 
            - DB_HOST=db-reddit
            - DEBUG=debug*
            - NODE_ENV=development
            - DECLUTTER_ENV=local
        tty: true
    db-reddit:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
