version: '3'

services: 
    declutter-reddit:
        build: . 
        command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 server.js
        volumes: 
            - .:/usr/src/app
        ports: 
            - "3000:3000"
            - "9229:9229"
        depends_on: 
            - db-reddit
            - migration
        environment: 
            - DB_HOST=db-reddit
            - DEBUG=debug*
        tty: true
    migration:
        build: .
        command: ./node_modules/.bin/knex --knexfile ./lib/database/knexfile.js migrate:latest
        depends_on: 
            - db-reddit
        environment: 
            - DB_HOST=db-reddit
    db-reddit:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=reddit_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=reddit
            - TZ=UTC