version: '3'

services: 
    declutter-reddit:
        build: . 
        command: ./node_modules/.bin/nodemon -L --inspect=0.0.0.0:9229 -r dotenv/config declutter-reddit.js
        volumes: 
            - .:/usr/src/app
        ports: 
            - "3000:3000"
            - "9229:9229"
        depends_on: 
            - db-reddit
        environment: 
            - DB_HOST=db-reddit
            - DEBUG=debug*
            - NODE_ENV=development
        tty: true
    db-reddit:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=reddit_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=reddit
            - TZ=UTC